###########
# site.title, site.author.name

title:  TickTackkkk
author:
  name: SS


########
# more settings

collections:
  chapters:
      output: false

markdown: kramdown

kramdown:
  auto_ids: true


sass:
  sass_dir: css
  style:    expanded


exclude:
- README.md


safe: true
lsi: false
